In [1]:
import requests
import json
import pprint
import pandas as pd
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 YaBrowser/19.6.1.153 Yowser/2.5 Safari/537.36'}

In [2]:
df_markets = pd.read_csv("tyler_diddy_polymarkets.csv", sep=";")
df_markets.columns

Index(['Unnamed: 0', 'id', 'slug', 'conditionId', 'liquidity', 'volume',
       'open_interest', 'volume24hr', 'volume1wk', 'volume1mo', 'volume1yr',
       'price_yes', 'price_no', 'oneWeekPriceChange'],
      dtype='str')

In [3]:
df_markets["conditionId"][0]

'0xdfea8851512360fb70c4b4ed29ed369b6dbcdfc58b2493b66cba65faab622129'

In [4]:
#Let's try calling the API first to know what info we get
h_url = "https://data-api.polymarket.com/holders"
params = {
    "market": df_markets["conditionId"][0]
}
response = requests.get(h_url, headers=headers, params=params)
test = response.json()
test[0]

{'token': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
 'holders': [{'proxyWallet': '0xa7a6cd5399040aa661ee595f4421337d80188117',
   'bio': '',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Unsteady-Drake',
   'amount': 10515.915772,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'KoloJones',
   'profileImage': '',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0xf44dcf50490507a44a6244dc07f50686e71060af',
   'bio': '',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Recent-Eveningwear',
   'amount': 6140.58,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'Certify0148',
   'profileImage': '',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0x44fccfc4f7653fc79c386d1bcb2181d730a4ac29',
   'bio': '',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Clean-Windscreen',
   'amount': 4881.27,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'darthgeek1338',
   'profileImage': '',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0xc8ab97a9089a9ff7e6ef0688e6e591a066946418',
   'bio': 'After the fight battle is fought, The legend of Billy the farmer will live forever.',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Hideous-Racer',
   'amount': 3294.142968,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'ArmageddonRewardsBilly',
   'profileImage': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/rewardsiconbilly_637fb65a-1112-49bc-9376-3fb6d377cde0_1738970845400.png',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0xfc1490c043e5ed6ec2ce7ea003e6b540b0eb2e9b',
   'bio': '',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Bountiful-Clinic',
   'amount': 3190.09,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'darthgeek',
   'profileImage': '',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0xd816393119a297874bff7304b9e222101f5a6c0f',
   'bio': '',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Ajar-Alarm',
   'amount': 2748.266036,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'bshardy',
   'profileImage': '',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0x7e31a5e9c31638483614e9fd9f945bb34692454d',
   'bio': '',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Unlucky-Pounding',
   'amount': 2500,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'Odysseus7',
   'profileImage': '',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0x0b644e443a404159a7b5ca4650cf2444b13549bd',
   'bio': '',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Homely-Amenity',
   'amount': 1999.995923,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'Gdub',
   'profileImage': '',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0xc22e6f366c977b213b0e0ea2583072aadaba54eb',
   'bio': '',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Academic-Sherbet',
   'amount': 1378.064439,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'Willie1',
   'profileImage': '',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0x0f2bcf469f85fe746058f3a0767d24124d0d665a',
   'bio': '',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Light-Hygienic',
   'amount': 999.969991,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'Sylvester.the.Cat',
   'profileImage': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/profile-image-8406618-1fdad8e0-1384-4a4b-8775-fc5d3972f1e0.png',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0xf17cd97d0316fd7c57b38db85a35548fd8a70c29',
   'bio': '',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Snappy-Warden',
   'amount': 974.389077,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'natstar',
   'profileImage': '',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0xe6fd18067d9b8768ee4dc45e926cf54867288bc3',
   'bio': '',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Easy-Koala',
   'amount': 800,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'Coldonn101',
   'profileImage': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/Screenshot_2024_12_11_at_17_10_51_The_Possible_Worlds_Tree___Predict_615a9af7-e2e7-4892-99cd-02b9bb7fe2b0_1737059861949.png',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0xd5b97d08ec6098407bfbf66c2786ccc9967fe44e',
   'bio': 'a general purpose, bi-pedal, autonomous humanoid robot capable of performing unsafe, repetitive or boring tasks',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Trained-Sniffle',
   'amount': 736.430965,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'Optimus-',
   'profileImage': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/profile-image-1526438-787bb0f2-bc16-4cd7-8d10-85af805f171d.jpg',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0x32d1623dddbd4841a98da71e47f0436d2ef2b949',
   'bio': 'All gas - no brakes                                                                                                             - Safety third',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Dear-Hypothesis',
   'amount': 704.99,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'rickyvaughn',
   'profileImage': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/profile-image-3065600-3674fbf3-3343-4498-9ea9-a329bdb05193.png',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0x9ad091ca2e8f1bd69f27662edcb49dceeaa5bf3d',
   'bio': '6720',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Kaleidoscopic-Hemisphere',
   'amount': 635.655003,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'PaddyAlpha',
   'profileImage': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/profile-image-1240150-e171f8d3-e9c2-4af9-bb16-c354c7c7fc3f.png',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0x3052776d06122dde8e1a86f2ed9defb97940232a',
   'bio': '',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': '',
   'amount': 602.533332,
   'displayUsernamePublic': False,
   'outcomeIndex': 0,
   'name': '',
   'profileImage': '',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0xae2b0aaea325a32870f56ff19df3b87acaa190ea',
   'bio': '',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Crowded-Jackal',
   'amount': 576.014317,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'TB14',
   'profileImage': '',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0x15fbd312f1925882ef83ba5aa69d7e2e5f6b252d',
   'bio': '',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Loving-Conclusion',
   'amount': 558.123639,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'monstur',
   'profileImage': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/profile-image-2654892-8b1eaccd-23b7-4cd6-8679-7e28bbea0fa2.jpeg',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0xc7d02944a76b9f83b199e9090ecc92c82d241f8a',
   'bio': '',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Flamboyant-Warming',
   'amount': 545.61,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': '0xc7D02944A76B9F83B199e9090ECC92C82d241F8a-1776944395495',
   'profileImage': '',
   'profileImageOptimized': '',
   'verified': False},
  {'proxyWallet': '0xeca0c0888e34df59589c67fbe53dc7f298b5e8f8',
   'bio': 'Tell me, what do I say to turn this around ? 🎶💃🏼',
   'asset': '110121849054524311559637722508594302357291606532161889048119752094089952931603',
   'pseudonym': 'Weird-Freedom',
   'amount': 516.976629,
   'displayUsernamePublic': True,
   'outcomeIndex': 0,
   'name': 'StarMaster',
   'profileImage': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/profile-image-3048498-41cd39ab-f0bd-4c1e-be28-c1293b6f5b9e.webp',
   'profileImageOptimized': '',
   'verified': False}]}

In [5]:
test[1]["holders"]
#test[0] contains yes-holders and test[1] contains no-holders

[{'proxyWallet': '0xe4de861d59e174d3d153a5968bc122c66f30c949',
  'bio': '',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Firsthand-Offense',
  'amount': 10000,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': 'On.The.Spectrum',
  'profileImage': '',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0x00d1bfdb216e363bdb1a04dc02865a4dd99ec8a4',
  'bio': '',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Any-Adviser',
  'amount': 5987.255074,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': 'placerv2',
  'profileImage': '',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0x96f795d0821b75a1c7f886b2c1cd49d108b7d6ae',
  'bio': '',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Weekly-Accounting',
  'amount': 5152.95095,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': 'ZaGambla',
  'profileImage': '',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0xb1ca909e848cc24ec4e220ce1c453bc290c51705',
  'bio': '',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Awesome-Availability',
  'amount': 3750.806511,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': 'NonceChaser',
  'profileImage': '',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0x6404bfa37fe830e29ee8967e1c3b2a8091d5f250',
  'bio': '',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Exalted-Beam',
  'amount': 3087.96,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': 'pop',
  'profileImage': '',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0x2b9dbf4b6e0e11309a9d6d2a09b72f65f652adc0',
  'bio': '',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Each-Jeans',
  'amount': 3073.46,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': 'seal7',
  'profileImage': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/profile-image-3929424-ce912f57-03a8-4a7f-91ce-3225cadda90a.png',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0x1f9e15f39bbd5d163b0eacf0fbef647ced9e4f1a',
  'bio': '',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Wan-Gymnastics',
  'amount': 2668.65735,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': 'Japanese-AI-Cat',
  'profileImage': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/profile-image-6144982-89008c50-542b-4ca5-a928-17d34d92d823.png',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0x760907c8840491c8c86fddb843d3f1d801786c4e',
  'bio': '',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Odd-Deformation',
  'amount': 2500,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': '0x760907C8840491c8C86fdDB843D3f1d801786C4e-1771959662080',
  'profileImage': '',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0xac4a1fabdac2438d6afa2a9e8e83845310a0bf1e',
  'bio': '@Montecarlospam on x',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Charming-Grape',
  'amount': 2103.303936,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': 'HerrieDavis',
  'profileImage': '',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0x524db836890e08aceb3abcdee98d44240e324495',
  'bio': '',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Distant-Inhibitor',
  'amount': 1793.11,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': '0x524db836890E08ACeB3AbcdEE98D44240E324495-1781873258241',
  'profileImage': '',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0x7e35a2a8cfd1eb1e69dacd043206db5a787f1a6c',
  'bio': '',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Unfit-Hardboard',
  'amount': 1537.338259,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': 'buoys',
  'profileImage': '',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0x5fa44ddbefd7c2962719dfbe14b9f164104dcd4e',
  'bio': 'No bettor, sometimes yes bettor',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Scrawny-Venture',
  'amount': 999.992179,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': 'ansatz',
  'profileImage': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/profile-image-5490368-370edcd7-7f74-41b4-90cb-0fa4facde1ab.webp',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0xbfbb9bdd654cb928a1b7b36e994bd53512a4dc2b',
  'bio': '',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Silent-Deck',
  'amount': 799.938845,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': 'LongShot-Louie',
  'profileImage': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/profile-image-931088-870f9109-9bbf-405c-a6da-9d3ae0ee04f9.png',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0x38390d45f459a7c4b413eb6e78bd57dbf8e7e2ee',
  'bio': 'Alt acc. Testing new signals. Polysights ❤️',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Immense-Gymnast',
  'amount': 673.076922,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': 'tre-polysights',
  'profileImage': '',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0xa8c63f775ddbbe66b56614191747def3021444e8',
  'bio': '',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Natural-Vacation',
  'amount': 499.991049,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': 'Tenebrus7',
  'profileImage': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/profile-image-561226-af4d2e36-9a46-4216-8305-ab6d8c97d1ce.png',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0xb1a2757fd88d6f66255f53565ada24d875b257fe',
  'bio': '',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Poor-Footage',
  'amount': 479.982221,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': 'HULK',
  'profileImage': '',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0xa0935ea62ba0820b43b3ebbf58a7d0de6b075d29',
  'bio': '',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Unruly-Plug',
  'amount': 405.555553,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': 'shorgio',
  'profileImage': '',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0xd423e340f159718145bcf5adb8028b0612bb99e9',
  'bio': '',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': '',
  'amount': 377.830187,
  'displayUsernamePublic': False,
  'outcomeIndex': 1,
  'name': '',
  'profileImage': '',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0x1da867ce1f1aafe706f543f67a6692ad5b35aa05',
  'bio': '',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'Front-Legislator-Birth',
  'amount': 348.935481,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': '0x1Da867ce1f1AaFe706f543F67a6692ad5B35Aa05-1775352334514',
  'profileImage': '',
  'profileImageOptimized': '',
  'verified': False},
 {'proxyWallet': '0x3825180182703613f3619d4611890c5b655504e8',
  'bio': '',
  'asset': '55924008678331392948336312806293360142875154524733691603322942979182976457930',
  'pseudonym': 'That-Macadamia',
  'amount': 347.99111,
  'displayUsernamePublic': True,
  'outcomeIndex': 1,
  'name': 'WhoseHouseRamsHouse',
  'profileImage': '',
  'profileImageOptimized': '',
  'verified': False}]

In [6]:
#Calling the API to get top holders of both markets
whale_master_list = []

for index, row in df_markets.iterrows():
    cond_id = row["conditionId"]
    market_title = row["slug"]

    h_url = f"https://data-api.polymarket.com/holders"
    params = {
        "market": cond_id,
        "limit": 100,
        "offset": 0,
    }
    response = requests.get(h_url, headers=headers, params=params)
    raw_holders = response.json()

    #THE API returns the yes holders first, so we set i == 0 to yes.
    for i, item in enumerate(raw_holders):
        if "holders" not in item:
            continue
    
        side = "YES" if i == 0 else "NO"
        
        #getting the holders data
        for holder in item["holders"]:
            whale_master_list.append(
                {
                "side": side,
                "market": market_title,
                "username": holder.get("pseudonym"),
                "wallet": holder.get("proxyWallet"),
                "shares": holder.get("amount"),
                "yes_no_index": holder.get("outcomeIndex"),
            }
            )
                
df_master_whales = pd.DataFrame(whale_master_list)

In [7]:
#Double checking shows that these were not actually usernames
df_master_whales["pseudonym"] = df_master_whales["username"]
df_master_whales = df_master_whales.drop(columns=["username"])

In [8]:
df_master_whales.to_csv("all_whales.csv")

In [9]:
df_master_whales

,side,market,wallet,shares,yes_no_index,pseudonym
0,YES,tyler-robinson-convicted-of-homicide,0xa7a6cd5399040aa661ee595f4421337d80188117,10515.915772,0,Unsteady-Drake
1,YES,tyler-robinson-convicted-of-homicide,0xf44dcf50490507a44a6244dc07f50686e71060af,6140.580000,0,Recent-Eveningwear
2,YES,tyler-robinson-convicted-of-homicide,0x44fccfc4f7653fc79c386d1bcb2181d730a4ac29,4881.270000,0,Clean-Windscreen
3,YES,tyler-robinson-convicted-of-homicide,0xc8ab97a9089a9ff7e6ef0688e6e591a066946418,3294.142968,0,Hideous-Racer
4,YES,tyler-robinson-convicted-of-homicide,0xfc1490c043e5ed6ec2ce7ea003e6b540b0eb2e9b,3190.090000,0,Bountiful-Clinic
...,...,...,...,...,...,...
305,NO,diddy-found-guilty-of-sex-trafficking,0xfe940ab2a3ad0b6e2295afb2b4c07f871369f965,5.000000,1,Straight-Ruler
306,NO,diddy-found-guilty-of-sex-trafficking,0x3774515d6f0e682434cf176886c1f4c0fc8478c4,3.448274,1,Aged-Suspect
307,NO,diddy-found-guilty-of-sex-trafficking,0x7bc927893bd89b981adfa4200b703a36958da102,2.857141,1,Full-Minimalism
308,NO,diddy-found-guilty-of-sex-trafficking,0xf7421c80e6212ae5127e74b932cc310b7e31be2d,2.857141,1,These-River
309,NO,diddy-found-guilty-of-sex-trafficking,0xd11762cc4d8954fe085103cd4a6a37219a256835,1.386554,1,Crisp-Myth

In [10]:
#Now we create a list of the top holders from each market
df_master_whales
df_tyler_filtered = df_master_whales[df_master_whales["market"] == "tyler-robinson-convicted-of-homicide"]

In [11]:
df_tyler_filtered

,side,market,wallet,shares,yes_no_index,pseudonym
0,YES,tyler-robinson-convicted-of-homicide,0xa7a6cd5399040aa661ee595f4421337d80188117,10515.915772,0,Unsteady-Drake
1,YES,tyler-robinson-convicted-of-homicide,0xf44dcf50490507a44a6244dc07f50686e71060af,6140.580000,0,Recent-Eveningwear
2,YES,tyler-robinson-convicted-of-homicide,0x44fccfc4f7653fc79c386d1bcb2181d730a4ac29,4881.270000,0,Clean-Windscreen
3,YES,tyler-robinson-convicted-of-homicide,0xc8ab97a9089a9ff7e6ef0688e6e591a066946418,3294.142968,0,Hideous-Racer
4,YES,tyler-robinson-convicted-of-homicide,0xfc1490c043e5ed6ec2ce7ea003e6b540b0eb2e9b,3190.090000,0,Bountiful-Clinic
...,...,...,...,...,...,...
195,NO,tyler-robinson-convicted-of-homicide,0x57b9acdde2dff37c39ad37f24f3293c8d2330464,5.447760,1,
196,NO,tyler-robinson-convicted-of-homicide,0xe6000afcee6ea70d272e3ca3517708add214a907,5.343282,1,
197,NO,tyler-robinson-convicted-of-homicide,0xe7505c94c7d5980919ad83b8e614142891094850,5.222221,1,
198,NO,tyler-robinson-convicted-of-homicide,0xcc1a5d9160199b0862fbe0870d211974a8d87044,5.149252,1,
199,NO,tyler-robinson-convicted-of-homicide,0x28ab2147f54270b141e6a0fc9c90043ded572048,5.106381,1,Super-Arena

In [12]:
#We do the same with the other market
df_master_whales
df_diddy_filtered = df_master_whales[df_master_whales["market"] == "diddy-found-guilty-of-sex-trafficking"]

In [13]:
len(df_diddy_filtered)

110

In [14]:
count_diddy_yes = (df_diddy_filtered["side"] == "YES").sum()
count_tyler_yes = (df_tyler_filtered["side"] == "YES").sum()
count_diddy_no = (df_diddy_filtered["side"] == "NO").sum()
count_tyler_no = (df_tyler_filtered["side"] == "NO").sum()
print(count_diddy_yes, count_tyler_yes, count_diddy_no, count_tyler_no)

100 100 10 100

In [15]:
#Double checking with the polymarket website it seems to be true that there were only 10 "no" holders for the diddy conviction market.

In [16]:
#Let's round the shares and then analyze the number of shares in each market
df_diddy_filtered["shares"] = df_diddy_filtered["shares"].round()
df_tyler_filtered["shares"] = df_tyler_filtered["shares"].round()
#Since there is an unequal amount of holders in these dfs we have to create new subsets.
df_tyler_yes = df_tyler_filtered[df_tyler_filtered["side"] == "YES"]
df_tyler_no = df_tyler_filtered[df_tyler_filtered["side"] == "NO"]
df_diddy_yes = df_diddy_filtered[df_diddy_filtered["side"] == "YES"]
df_diddy_no = df_diddy_filtered[df_diddy_filtered["side"] == "NO"]

In [17]:
import matplotlib.pyplot as plt

In [18]:
#Adding up the total shares kept by the top 100 holders on the leading side in both markets
tot_leading_shares = (df_tyler_no["shares"].sum()) + (df_diddy_yes["shares"].sum())
print(f"The 100 biggest yes-holders for the diddy-market and 100 biggest no-holders for Robinson together held {tot_leading_shares} shares.")

The 100 biggest yes-holders for the diddy-market and 100 biggest no-holders for Robinson together held 242728.0 shares.

In [19]:
#Since we know the volume of both markets (which is the same as shares traded)
#We can check how much of the total market is with the 100 biggest holders
tyler_vol = 177352
diddy_vol = 797961
df_tyler_filtered = df_tyler_filtered.sort_values("shares", ascending=False)
df_diddy_filtered = df_diddy_filtered.sort_values("shares", ascending=False)
df_diddy_filtered.head(10)

,side,market,wallet,shares,yes_no_index,pseudonym
200,YES,diddy-found-guilty-of-sex-trafficking,0xc1b02266e94b87473cd4e38a61f13c69bf5a4535,131519.0,0,Squiggly-Bonding
201,YES,diddy-found-guilty-of-sex-trafficking,0x2e7f06e8b568b9a04e152a549500e6a54f99b1d4,36258.0,0,
202,YES,diddy-found-guilty-of-sex-trafficking,0x65bf3bfd2cd0506e8e41752a01e7af7817c94b91,6000.0,0,Masculine-Pinot
203,YES,diddy-found-guilty-of-sex-trafficking,0x157fa171d15d3b9f9783a0c3f8700c95a12b5b27,4386.0,0,
204,YES,diddy-found-guilty-of-sex-trafficking,0xcf7c3d0c796b2aaaccfd613236431a0ec7cdf2cb,3000.0,0,Menacing-Hope
205,YES,diddy-found-guilty-of-sex-trafficking,0x7fda167dcaa5ffe2c6c34791c103c4bfcee3e430,2600.0,0,Rigid-Weight
206,YES,diddy-found-guilty-of-sex-trafficking,0xf6d8e74e76e79dcc7061c20824113cec164114ab,1504.0,0,Whopping-Manufacturing
207,YES,diddy-found-guilty-of-sex-trafficking,0xccdac3c7b285bb9402bee9e0e58fe76480af4937,1243.0,0,Overcooked-Diaphragm
208,YES,diddy-found-guilty-of-sex-trafficking,0x00fa1da7d2b8baa703a1d3554b5d1338be9030be,857.0,0,Delirious-Buzzard
209,YES,diddy-found-guilty-of-sex-trafficking,0x477a7d28ed844984088129207c0afcb2459e2d8e,450.0,0,Fair-Record

In [20]:
print(f"The top 100 holders of the Tyler market holds {((df_tyler_filtered["shares"].head(100).sum()) / 177352) * 100} percent of the total market.")
print(f"The top 100 holders of the Diddy market held {((df_diddy_filtered["shares"].head(100).sum()) / 797961) * 100} percent of the total market.")

The top 100 holders of the Tyler market holds 55.97625062023547 percent of the total market.
The top 100 holders of the Diddy market held 24.05430841858186 percent of the total market.

In [21]:
print(f"The top 10 holders of the Tyler market holds {((df_tyler_filtered["shares"].head(10).sum()) / 177352) * 100} percent of the total market.")
print(f"The top 10 holders of the Diddy market held {((df_diddy_filtered["shares"].head(10).sum()) / 797961) * 100} percent of the total market.")

The top 10 holders of the Tyler market holds 31.576187468988227 percent of the total market.
The top 10 holders of the Diddy market held 23.537115222423154 percent of the total market.

In [22]:
#The Tyler Robinson market is more evenly spread out.
#Maybe that says something about the increasing mainstream-ness of prediction markets.

In [23]:
market_holdings = {
    "market": ["tyler_market", "diddy_market"],
    "total_shares": [177352, 797961],
    "top_100_shares": [df_tyler_filtered["shares"].head(100).sum(), df_diddy_filtered["shares"].head(100).sum()],
    "top_100_perc": [((df_tyler_filtered["shares"].head(100).sum()) / 177352) * 100, ((df_diddy_filtered["shares"].head(100).sum()) / 797961) * 100],
    "top_10_shares": [df_tyler_filtered["shares"].head(10).sum(), df_diddy_filtered["shares"].head(10).sum()],
    "top_10_perc": [((df_tyler_filtered["shares"].head(10).sum()) / 177352) * 100, ((df_diddy_filtered["shares"].head(10).sum()) / 797961) * 100],
    "top_diff": [df_tyler_filtered["shares"].head(100).sum() - df_tyler_filtered["shares"].head(10).sum(), df_diddy_filtered["shares"].head(100).sum() - df_diddy_filtered["shares"].head(10).sum()],
    "top_diff_perc": [((df_tyler_filtered["shares"].head(100).sum()) / 177352) * 100 - ((df_tyler_filtered["shares"].head(10).sum()) / 177352) * 100,
                      ((df_diddy_filtered["shares"].head(100).sum()) / 797961) * 100 - ((df_diddy_filtered["shares"].head(10).sum()) / 797961) * 100],
}

In [24]:
market_holdings = pd.DataFrame(market_holdings)
#I realized that the API was giving me bad data for the diddy_market so we are removing it from the df.
market_holdings = market_holdings[market_holdings["market"] != "diddy_market"]
market_holdings

,market,total_shares,top_100_shares,top_100_perc,top_10_shares,top_10_perc,top_diff,top_diff_perc
0,tyler_market,177352,99275.0,55.976251,56001.0,31.576187,43274.0,24.400063

In [25]:
market_holdings_chart = market_holdings.drop(columns=["total_shares", "market", "top_100_shares", "top_10_shares", "top_diff", "top_diff_perc"])

In [26]:
market_holdings_chart["top_100_perc"] = (market_holdings_chart["top_100_perc"]) - (market_holdings_chart["top_10_perc"])
market_holdings_chart["rest"] = 100 - ((market_holdings_chart["top_100_perc"]) + (market_holdings_chart["top_10_perc"]))
market_holdings_chart

   top_100_perc  top_10_perc       rest
0     24.400063    31.576187  44.023749

In [27]:
market_holdings_chart.to_csv("market_holdings_chart_tyler_diddy.csv")

In [28]:
df_diddy_filtered.to_csv("diddy_holders_filtered.csv")
df_tyler_filtered.to_csv("tyler_holders_filtered.csv")

In [29]:
#let's see if there are people who traded both markets
tyler_wallets = set(df_tyler_filtered["wallet"].astype(str).str.lower().str.strip())
diddy_wallets = set(df_diddy_filtered["wallet"].astype(str).str.lower().str.strip())
overlap = diddy_wallets.intersection(tyler_wallets)
len(overlap)

0

In [30]:
#We double check with another method that there really isn't any overlapping traders
df_overlap = pd.merge(
    df_diddy_filtered, df_tyler_filtered, on="wallet", suffixes=("_diddy", "_tyler")
)

# Clean up the output to see the most important comparison columns
comparison_view = df_overlap[
    [
        "wallet",
        "pseudonym_diddy",
        "shares_diddy",
        "side_diddy",
        "pseudonym_tyler",
        "shares_tyler",
        "side_tyler",
    ]
]
print(f"Found {len(comparison_view)} overlapping traders!")
print(comparison_view.head())

Found 0 overlapping traders!
Empty DataFrame
Columns: [wallet, pseudonym_diddy, shares_diddy, side_diddy, pseudonym_tyler, shares_tyler, side_tyler]
Index: []

In [31]:
df_top_ten = pd.concat([df_tyler_filtered.head(10), df_diddy_filtered.head(10)], ignore_index=True)
df_top_ten.to_csv("top_ten_whales_both.csv")